# Generated by Django 5.1.3 on 2025-02-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='products',
        ),
    ]
