# Generated by Django 5.1.3 on 2025-03-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_package_products_delete_packageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
