# Generated by Django 5.1.3 on 2025-03-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_package_price_remove_package_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='products',
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.DeleteModel(
            name='PackageProduct',
        ),
        migrations.AddField(
            model_name='package',
            name='products',
            field=models.JSONField(default=list, null=True),
        ),
    ]
