# Generated by Django 5.1.3 on 2025-03-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_remove_package_products_alter_package_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='stock_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
