# Generated by Django 5.1.3 on 2025-02-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='catalogue_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='measurement_unit',
            field=models.CharField(choices=[('grams', 'Grams'), ('kilograms', 'Kilograms'), ('milliliters', 'Milliliters'), ('liters', 'Liters'), ('pieces', 'Pieces')], default='grams', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_measurement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Proteins', 'Proteins'), ('Dairy', 'Dairy'), ('HerbsAndSpices', 'Herbs and Spices'), ('OilsAndVinegars', 'Oils and Vinegars'), ('NutsAndSeeds', 'Nuts and Seeds'), ('Condiments', 'Condiments')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('LeafyGreens', 'Leafy Greens'), ('Cruciferous', 'Cruciferous'), ('Root', 'Root Vegetables'), ('Allium', 'Alliums'), ('Nightshades', 'Nightshades'), ('Legumes', 'Legumes'), ('Mushrooms', 'Mushrooms'), ('Squashes', 'Squashes'), ('Citrus', 'Citrus'), ('Tropical', 'Tropical Fruits'), ('Berries', 'Berries'), ('StoneFruits', 'Stone Fruits'), ('Pomes', 'Pome Fruits'), ('Melons', 'Melons'), ('WholeGrains', 'Whole Grains'), ('Pasta', 'Pasta'), ('Breads', 'Breads'), ('Meat', 'Meat'), ('Seafood', 'Seafood'), ('PlantBased', 'Plant-Based Proteins'), ('Milk', 'Milk'), ('Cheese', 'Cheese'), ('Yogurt', 'Yogurt'), ('Herbs', 'Herbs'), ('Spices', 'Spices'), ('Oils', 'Oils'), ('Vinegars', 'Vinegars'), ('Nuts', 'Nuts'), ('Seeds', 'Seeds'), ('Sauces', 'Sauces'), ('Pastes', 'Pastes')], max_length=50),
        ),
    ]
