# Generated by Django 5.1.3 on 2025-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saladouser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='saladouser',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company'),
        ),
    ]
